version: "2.2"

services:
# Configuration for the Apache2 server
  apache2:
    container_name: apache2
    build: Apache2
    ports:
      - "8000:80"
    volumes:
      - ./Apache2/appdatas/:/var/www/localhost/htdocs/
    depends_on:
      - mariadb

# Configuration for the MariaDB server
  mariadb:
    container_name: mariadb
    build: BDD
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - ./BDD/bdddatas/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hello
    networks:
      - networkName

# Configuration for phpmyadmin web app
  phpmyadmin:
      image: phpmyadmin:5.1-apache
      container_name: phpmyadmin
      depends_on: 
      - mariadb
      environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      restart: always
      ports:
      - 8080:80
      links: 
      - "mariadb"
      networks:
      - networkName

networks:
  networkName:
    name: networkName